# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# "$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["<Enter>"]
run = "plugin smart-enter"
desc = "Enter the child directory, or open the selected file"

[[mgr.prepend_keymap]]
on = ["<Backspace>"]
run = "leave"
desc = "Go back to the parent directory"

[[mgr.prepend_keymap]]
on = ["<C-j>"]
run = "seek 5"
desc = "Seek forward 5 in glow files"

[[mgr.prepend_keymap]]
on = ["<C-k>"]
run = "seek -5"
desc = "Seek backwards 5 lines in md files"

[[mgr.prepend_keymap]]
on = ["R","b"]
run = "plugin recycle-bin"
desc = "Open Recycle Bin menu"
